apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
- ingress.yaml
images:
- name: ghcr.io/kingdonb/sites/workflow
  newName: ghcr.io/kingdonb/sites/workflow
  newTag: serve
